"""Reference master data used to keep synthetic records geographically and commercially realistic."""

from __future__ import annotations

AIRCRAFT_MODELS: tuple[tuple[str, str, int], ...] = (
    ("Airbus", "A320neo", 180),
    ("Airbus", "A321neo", 220),
    ("Airbus", "A330-300", 290),
    ("Airbus", "A350-900", 325),
    ("Boeing", "737-800", 175),
    ("Boeing", "737 MAX 8", 178),
    ("Boeing", "787-9", 290),
    ("Boeing", "777-300ER", 350),
    ("Embraer", "E175", 76),
    ("Embraer", "E190", 100),
)

ALLIANCES = ("Star Alliance", "oneworld", "SkyTeam", "none")

LOYALTY_TIERS = ("standard", "silver", "gold", "platinum")
LOYALTY_WEIGHTS = (0.62, 0.22, 0.12, 0.04)

CABIN_CLASSES = ("economy", "premium_economy", "business", "first")
PAYMENT_METHODS = ("card", "wallet", "miles", "bank_transfer")
CANCELLATION_REASONS = ("weather", "mechanical", "crew", "atc", "security", "other")

# iata, icao, name, city, country, region, timezone, lat, lon
AIRPORTS: tuple[tuple[str, str, str, str, str, str, str, float, float], ...] = (
    ("ATL", "KATL", "Hartsfield-Jackson Atlanta International", "Atlanta", "United States", "North America", "America/New_York", 33.6407, -84.4277),
    ("LAX", "KLAX", "Los Angeles International", "Los Angeles", "United States", "North America", "America/Los_Angeles", 33.9416, -118.4085),
    ("ORD", "KORD", "Chicago O'Hare International", "Chicago", "United States", "North America", "America/Chicago", 41.9742, -87.9073),
    ("DFW", "KDFW", "Dallas/Fort Worth International", "Dallas", "United States", "North America", "America/Chicago", 32.8998, -97.0403),
    ("DEN", "KDEN", "Denver International", "Denver", "United States", "North America", "America/Denver", 39.8561, -104.6737),
    ("JFK", "KJFK", "John F. Kennedy International", "New York", "United States", "North America", "America/New_York", 40.6413, -73.7781),
    ("SFO", "KSFO", "San Francisco International", "San Francisco", "United States", "North America", "America/Los_Angeles", 37.6213, -122.3790),
    ("SEA", "KSEA", "Seattle-Tacoma International", "Seattle", "United States", "North America", "America/Los_Angeles", 47.4502, -122.3088),
    ("MIA", "KMIA", "Miami International", "Miami", "United States", "North America", "America/New_York", 25.7959, -80.2870),
    ("BOS", "KBOS", "Boston Logan International", "Boston", "United States", "North America", "America/New_York", 42.3656, -71.0096),
    ("EWR", "KEWR", "Newark Liberty International", "Newark", "United States", "North America", "America/New_York", 40.6895, -74.1745),
    ("IAH", "KIAH", "George Bush Intercontinental", "Houston", "United States", "North America", "America/Chicago", 29.9902, -95.3368),
    ("PHX", "KPHX", "Phoenix Sky Harbor International", "Phoenix", "United States", "North America", "America/Phoenix", 33.4352, -112.0101),
    ("CLT", "KCLT", "Charlotte Douglas International", "Charlotte", "United States", "North America", "America/New_York", 35.2140, -80.9431),
    ("LAS", "KLAS", "Harry Reid International", "Las Vegas", "United States", "North America", "America/Los_Angeles", 36.0840, -115.1537),
    ("MSP", "KMSP", "Minneapolis-Saint Paul International", "Minneapolis", "United States", "North America", "America/Chicago", 44.8848, -93.2223),
    ("DTW", "KDTW", "Detroit Metropolitan Wayne County", "Detroit", "United States", "North America", "America/New_York", 42.2162, -83.3554),
    ("PHL", "KPHL", "Philadelphia International", "Philadelphia", "United States", "North America", "America/New_York", 39.8744, -75.2424),
    ("LGA", "KLGA", "LaGuardia", "New York", "United States", "North America", "America/New_York", 40.7769, -73.8740),
    ("BWI", "KBWI", "Baltimore/Washington International", "Baltimore", "United States", "North America", "America/New_York", 39.1774, -76.6684),
    ("SAN", "KSAN", "San Diego International", "San Diego", "United States", "North America", "America/Los_Angeles", 32.7338, -117.1933),
    ("TPA", "KTPA", "Tampa International", "Tampa", "United States", "North America", "America/New_York", 27.9755, -82.5332),
    ("PDX", "KPDX", "Portland International", "Portland", "United States", "North America", "America/Los_Angeles", 45.5898, -122.5951),
    ("HNL", "PHNL", "Daniel K. Inouye International", "Honolulu", "United States", "North America", "Pacific/Honolulu", 21.3245, -157.9251),
    ("YYZ", "CYYZ", "Toronto Pearson International", "Toronto", "Canada", "North America", "America/Toronto", 43.6777, -79.6248),
    ("YVR", "CYVR", "Vancouver International", "Vancouver", "Canada", "North America", "America/Vancouver", 49.1947, -123.1792),
    ("YUL", "CYUL", "Montreal-Pierre Elliott Trudeau", "Montreal", "Canada", "North America", "America/Toronto", 45.4706, -73.7408),
    ("MEX", "MMMX", "Mexico City International", "Mexico City", "Mexico", "North America", "America/Mexico_City", 19.4363, -99.0721),
    ("CUN", "MMUN", "Cancun International", "Cancun", "Mexico", "North America", "America/Cancun", 21.0365, -86.8771),
    ("LHR", "EGLL", "London Heathrow", "London", "United Kingdom", "Europe", "Europe/London", 51.4700, -0.4543),
    ("LGW", "EGKK", "London Gatwick", "London", "United Kingdom", "Europe", "Europe/London", 51.1537, -0.1821),
    ("MAN", "EGCC", "Manchester", "Manchester", "United Kingdom", "Europe", "Europe/London", 53.3537, -2.2750),
    ("CDG", "LFPG", "Paris Charles de Gaulle", "Paris", "France", "Europe", "Europe/Paris", 49.0097, 2.5479),
    ("ORY", "LFPO", "Paris Orly", "Paris", "France", "Europe", "Europe/Paris", 48.7233, 2.3794),
    ("AMS", "EHAM", "Amsterdam Schiphol", "Amsterdam", "Netherlands", "Europe", "Europe/Amsterdam", 52.3105, 4.7683),
    ("FRA", "EDDF", "Frankfurt am Main", "Frankfurt", "Germany", "Europe", "Europe/Berlin", 50.0379, 8.5622),
    ("MUC", "EDDM", "Munich", "Munich", "Germany", "Europe", "Europe/Berlin", 48.3538, 11.7861),
    ("MAD", "LEMD", "Adolfo Suarez Madrid-Barajas", "Madrid", "Spain", "Europe", "Europe/Madrid", 40.4983, -3.5676),
    ("BCN", "LEBL", "Barcelona-El Prat", "Barcelona", "Spain", "Europe", "Europe/Madrid", 41.2974, 2.0833),
    ("FCO", "LIRF", "Rome Fiumicino", "Rome", "Italy", "Europe", "Europe/Rome", 41.8003, 12.2389),
    ("MXP", "LIMC", "Milan Malpensa", "Milan", "Italy", "Europe", "Europe/Rome", 45.6306, 8.7281),
    ("ZRH", "LSZH", "Zurich", "Zurich", "Switzerland", "Europe", "Europe/Zurich", 47.4582, 8.5555),
    ("VIE", "LOWW", "Vienna International", "Vienna", "Austria", "Europe", "Europe/Vienna", 48.1103, 16.5697),
    ("CPH", "EKCH", "Copenhagen Kastrup", "Copenhagen", "Denmark", "Europe", "Europe/Copenhagen", 55.6180, 12.6508),
    ("ARN", "ESSA", "Stockholm Arlanda", "Stockholm", "Sweden", "Europe", "Europe/Stockholm", 59.6498, 17.9238),
    ("OSL", "ENGM", "Oslo Gardermoen", "Oslo", "Norway", "Europe", "Europe/Oslo", 60.1976, 11.1004),
    ("HEL", "EFHK", "Helsinki-Vantaa", "Helsinki", "Finland", "Europe", "Europe/Helsinki", 60.3172, 24.9633),
    ("DUB", "EIDW", "Dublin", "Dublin", "Ireland", "Europe", "Europe/Dublin", 53.4264, -6.2499),
    ("LIS", "LPPT", "Lisbon Humberto Delgado", "Lisbon", "Portugal", "Europe", "Europe/Lisbon", 38.7756, -9.1354),
    ("ATH", "LGAV", "Athens International", "Athens", "Greece", "Europe", "Europe/Athens", 37.9356, 23.9484),
    ("IST", "LTFM", "Istanbul Airport", "Istanbul", "Turkey", "Europe", "Europe/Istanbul", 41.2753, 28.7519),
    ("DXB", "OMDB", "Dubai International", "Dubai", "United Arab Emirates", "Middle East", "Asia/Dubai", 25.2532, 55.3657),
    ("AUH", "OMAA", "Abu Dhabi International", "Abu Dhabi", "United Arab Emirates", "Middle East", "Asia/Dubai", 24.4330, 54.6511),
    ("DOH", "OTHH", "Hamad International", "Doha", "Qatar", "Middle East", "Asia/Qatar", 25.2609, 51.6138),
    ("DEL", "VIDP", "Indira Gandhi International", "Delhi", "India", "Asia", "Asia/Kolkata", 28.5562, 77.1000),
    ("BOM", "VABB", "Chhatrapati Shivaji Maharaj International", "Mumbai", "India", "Asia", "Asia/Kolkata", 19.0896, 72.8656),
    ("BLR", "VOBL", "Kempegowda International", "Bengaluru", "India", "Asia", "Asia/Kolkata", 13.1986, 77.7066),
    ("HYD", "VOHS", "Rajiv Gandhi International", "Hyderabad", "India", "Asia", "Asia/Kolkata", 17.2403, 78.4294),
    ("MAA", "VOMM", "Chennai International", "Chennai", "India", "Asia", "Asia/Kolkata", 12.9941, 80.1709),
    ("SIN", "WSSS", "Singapore Changi", "Singapore", "Singapore", "Asia", "Asia/Singapore", 1.3644, 103.9915),
    ("HKG", "VHHH", "Hong Kong International", "Hong Kong", "Hong Kong", "Asia", "Asia/Hong_Kong", 22.3080, 113.9185),
    ("NRT", "RJAA", "Narita International", "Tokyo", "Japan", "Asia", "Asia/Tokyo", 35.7720, 140.3929),
    ("HND", "RJTT", "Tokyo Haneda", "Tokyo", "Japan", "Asia", "Asia/Tokyo", 35.5494, 139.7798),
    ("ICN", "RKSI", "Seoul Incheon International", "Seoul", "South Korea", "Asia", "Asia/Seoul", 37.4602, 126.4407),
    ("PEK", "ZBAA", "Beijing Capital International", "Beijing", "China", "Asia", "Asia/Shanghai", 40.0799, 116.6031),
    ("PVG", "ZSPD", "Shanghai Pudong International", "Shanghai", "China", "Asia", "Asia/Shanghai", 31.1443, 121.8083),
    ("BKK", "VTBS", "Suvarnabhumi", "Bangkok", "Thailand", "Asia", "Asia/Bangkok", 13.6900, 100.7501),
    ("KUL", "WMKK", "Kuala Lumpur International", "Kuala Lumpur", "Malaysia", "Asia", "Asia/Kuala_Lumpur", 2.7456, 101.7099),
    ("SYD", "YSSY", "Sydney Kingsford Smith", "Sydney", "Australia", "Oceania", "Australia/Sydney", -33.9399, 151.1753),
    ("MEL", "YMML", "Melbourne", "Melbourne", "Australia", "Oceania", "Australia/Melbourne", -37.6690, 144.8410),
    ("AKL", "NZAA", "Auckland", "Auckland", "New Zealand", "Oceania", "Pacific/Auckland", -37.0082, 174.7850),
    ("GRU", "SBGR", "Sao Paulo/Guarulhos", "Sao Paulo", "Brazil", "South America", "America/Sao_Paulo", -23.4356, -46.4731),
    ("GIG", "SBGL", "Rio de Janeiro Galeao", "Rio de Janeiro", "Brazil", "South America", "America/Sao_Paulo", -22.8090, -43.2506),
    ("EZE", "SAEZ", "Buenos Aires Ministro Pistarini", "Buenos Aires", "Argentina", "South America", "America/Argentina/Buenos_Aires", -34.8222, -58.5358),
    ("BOG", "SKBO", "El Dorado International", "Bogota", "Colombia", "South America", "America/Bogota", 4.7016, -74.1469),
    ("LIM", "SPJC", "Jorge Chavez International", "Lima", "Peru", "South America", "America/Lima", -12.0219, -77.1143),
    ("SCL", "SCEL", "Santiago Arturo Merino Benitez", "Santiago", "Chile", "South America", "America/Santiago", -33.3930, -70.7858),
    ("JNB", "FAOR", "O. R. Tambo International", "Johannesburg", "South Africa", "Africa", "Africa/Johannesburg", -26.1367, 28.2411),
    ("CPT", "FACT", "Cape Town International", "Cape Town", "South Africa", "Africa", "Africa/Johannesburg", -33.9715, 18.6021),
    ("CAI", "HECA", "Cairo International", "Cairo", "Egypt", "Africa", "Africa/Cairo", 30.1127, 31.4000),
    ("NBO", "HKJK", "Jomo Kenyatta International", "Nairobi", "Kenya", "Africa", "Africa/Nairobi", -1.3192, 36.9278),
    ("ADD", "HAAB", "Addis Ababa Bole International", "Addis Ababa", "Ethiopia", "Africa", "Africa/Addis_Ababa", 8.9779, 38.7993),
    ("LOS", "DNMM", "Murtala Muhammed International", "Lagos", "Nigeria", "Africa", "Africa/Lagos", 6.5774, 3.3212),
)

# iata, icao, name, country, alliance, hq city, founded
AIRLINES: tuple[tuple[str, str, str, str, str, str, int], ...] = (
    ("DL", "DAL", "Delta Air Lines", "United States", "SkyTeam", "Atlanta", 1924),
    ("AA", "AAL", "American Airlines", "United States", "oneworld", "Fort Worth", 1930),
    ("UA", "UAL", "United Airlines", "United States", "Star Alliance", "Chicago", 1926),
    ("WN", "SWA", "Southwest Airlines", "United States", "none", "Dallas", 1967),
    ("B6", "JBU", "JetBlue Airways", "United States", "none", "New York", 1998),
    ("AS", "ASA", "Alaska Airlines", "United States", "oneworld", "Seattle", 1932),
    ("AC", "ACA", "Air Canada", "Canada", "Star Alliance", "Montreal", 1937),
    ("BA", "BAW", "British Airways", "United Kingdom", "oneworld", "London", 1974),
    ("AF", "AFR", "Air France", "France", "SkyTeam", "Paris", 1933),
    ("KL", "KLM", "KLM Royal Dutch Airlines", "Netherlands", "SkyTeam", "Amsterdam", 1919),
    ("LH", "DLH", "Lufthansa", "Germany", "Star Alliance", "Frankfurt", 1953),
    ("IB", "IBE", "Iberia", "Spain", "oneworld", "Madrid", 1927),
    ("AZ", "ITY", "ITA Airways", "Italy", "SkyTeam", "Rome", 2020),
    ("LX", "SWR", "Swiss International Air Lines", "Switzerland", "Star Alliance", "Zurich", 2002),
    ("SK", "SAS", "Scandinavian Airlines", "Sweden", "SkyTeam", "Stockholm", 1946),
    ("EI", "EIN", "Aer Lingus", "Ireland", "none", "Dublin", 1936),
    ("TK", "THY", "Turkish Airlines", "Turkey", "Star Alliance", "Istanbul", 1933),
    ("EK", "UAE", "Emirates", "United Arab Emirates", "none", "Dubai", 1985),
    ("QR", "QTR", "Qatar Airways", "Qatar", "oneworld", "Doha", 1993),
    ("EY", "ETD", "Etihad Airways", "United Arab Emirates", "none", "Abu Dhabi", 2003),
    ("AI", "AIC", "Air India", "India", "Star Alliance", "Delhi", 1932),
    ("6E", "IGO", "IndiGo", "India", "none", "Gurugram", 2006),
    ("SQ", "SIA", "Singapore Airlines", "Singapore", "Star Alliance", "Singapore", 1972),
    ("CX", "CPA", "Cathay Pacific", "Hong Kong", "oneworld", "Hong Kong", 1946),
    ("NH", "ANA", "All Nippon Airways", "Japan", "Star Alliance", "Tokyo", 1952),
    ("JL", "JAL", "Japan Airlines", "Japan", "oneworld", "Tokyo", 1951),
    ("KE", "KAL", "Korean Air", "South Korea", "SkyTeam", "Seoul", 1969),
    ("QF", "QFA", "Qantas", "Australia", "oneworld", "Sydney", 1920),
    ("NZ", "ANZ", "Air New Zealand", "New Zealand", "Star Alliance", "Auckland", 1940),
    ("LA", "LAN", "LATAM Airlines", "Chile", "none", "Santiago", 1929),
    ("G3", "GLO", "GOL Linhas Aereas", "Brazil", "none", "Sao Paulo", 2000),
    ("SA", "SAA", "South African Airways", "South Africa", "none", "Johannesburg", 1934),
    ("ET", "ETH", "Ethiopian Airlines", "Ethiopia", "Star Alliance", "Addis Ababa", 1945),
    ("MS", "MSR", "Egyptair", "Egypt", "Star Alliance", "Cairo", 1932),
    ("KQ", "KQA", "Kenya Airways", "Kenya", "SkyTeam", "Nairobi", 1977),
)
